version: '3.8'

services:
  ping-admin-exporter:
    restart: unless-stopped
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        VERSION: "local-build"

    image: ping-admin-exporter:local

    ports:
      - "8080:8080"

    env_file:
      - .env

networks:
  default:
    name: ping-admin-exporter-net